'use strict';

module.exports = {
  AbortController,
  AbortSignal,
  Blob,
  BroadcastChannel,
  Buffer,
  ByteLengthQueuingStrategy,
  clearImmediate,
  clearInterval,
  clearTimeout,
  CompressionStream,
  CountQueuingStrategy,
  DecompressionStream,
  Event,
  EventTarget,
  fetch,
  FormData,
  Headers,
  MessageChannel,
  MessageEvent,
  MessagePort,
  queueMicrotask,
  Request,
  Response,
  setImmediate,
  setInterval,
  setTimeout,
  TextDecoder,
  TextDecoderStream,
  TextEncoder,
  TextEncoderStream,
  URL,
  URLSearchParams,
  WebAssembly,
};
